Repository crpoudyal/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#12 Added Image Resizer
  python/image_resizer.py
Labels: hacktoberfest

#13 PigeionHole Sort
  python/Pegionhole_sort.py
Labels: hacktoberfest

#15 N-Queen Code using backtracking
  N-Queen.py
Labels: hacktoberfest

#14 Largest Rectangle in Histogram using Stack
  java/Largest Rectangle in histogram.java
Labels: hacktoberfest

#18 feat : traversing a collection using iterator object
  dart/traversing.dart
Labels: hacktoberfest

#16 Diameter of Binary Tree
  Diameter-of-binary-tree.java
Labels: hacktoberfest

#19 Create Ling Shortner and Text Shortner GUI and QR code
  python/Link_Shortner_GUI.py
  python/QR_Code_Generator.py
Labels: hacktoberfest

#17 added 2 Competitive programing java codes
  java/TravellingSalesMan.java
  java/diningphil.java
Labels: hacktoberfest

#20 feat: Abstract Class in Dart
  dart/abstractClass.dart
Labels: hacktoberfest

#22 CLI Password Generator
  python/password_generator.py
Labels: enhancement, hacktoberfest

#24 Create asteroid game.py
  asteroid game.py
Labels: hacktoberfest, hacktoberfest-accepted

#25 Author name Added
  python/Facial_Recognition.py
  python/QR_Code_Generator.py
Labels: hacktoberfest, hacktoberfest-accepted

#26 Virtual Painter added
  python/Facial_expression_recognition.py
  python/tools.png
  python/virtual_paint_app.py
Labels: hacktoberfest, hacktoberfest-accepted

#31 feat: gRPC : Hello world
  mn/firstapplication/.gitignore
  mn/firstapplication/README.md
  mn/firstapplication/build.gradle
  mn/firstapplication/gradle.properties
  mn/firstapplication/gradle/wrapper/gradle-wrapper.jar
  mn/firstapplication/gradle/wrapper/gradle-wrapper.properties
  mn/firstapplication/gradlew
  mn/firstapplication/gradlew.bat
  mn/firstapplication/micronaut-cli.yml
  mn/firstapplication/settings.gradle
  mn/firstapplication/src/main/java/grpcdemo/Application.java
  mn/firstapplication/src/main/java/grpcdemo/GrpcClient.java
  mn/firstapplication/src/main/java/grpcdemo/GrpcServer.java
  mn/firstapplication/src/main/java/grpcdemo/HelloServiceImpl.java
  mn/firstapplication/src/main/proto/firstapplication.proto
  mn/firstapplication/src/main/resources/application.yml
  mn/firstapplication/src/main/resources/logback.xml
  mn/firstapplication/src/test/java/grpcdemo/FirstapplicationTest.java
Labels: hacktoberfest, hacktoberfest-accepted

#27 Create currency_converter.py
  currency_converter.py
Labels: hacktoberfest, hacktoberfest-accepted

#29 Added Digital Clock in GUI mode
  python/Digital_Clock.py
Labels: hacktoberfest, hacktoberfest-accepted

#30 Added Minesweeper game
  python/Minesweeper.py
Labels: hacktoberfest, hacktoberfest-accepted

#32 Text Detector using OCR
  python/text_detector.py
Labels: hacktoberfest, hacktoberfest-accepted

#34 Flight finder application added
  AndroidProject/FlightFinder/.gitignore
  AndroidProject/FlightFinder/.idea/.gitignore
  AndroidProject/FlightFinder/.idea/compiler.xml
  AndroidProject/FlightFinder/.idea/deploymentTargetDropDown.xml
  AndroidProject/FlightFinder/.idea/gradle.xml
  AndroidProject/FlightFinder/.idea/misc.xml
  AndroidProject/FlightFinder/app/.gitignore
  AndroidProject/FlightFinder/app/build.gradle
  AndroidProject/FlightFinder/app/proguard-rules.pro
  AndroidProject/FlightFinder/app/src/androidTest/java/com/example/flightfinder/ExampleInstrumentedTest.kt
  AndroidProject/FlightFinder/app/src/main/AndroidManifest.xml
  AndroidProject/FlightFinder/app/src/main/java/com/example/flightfinder/MainActivity.kt
  AndroidProject/FlightFinder/app/src/main/java/com/example/flightfinder/Mutlipleresources.kt
  AndroidProject/FlightFinder/app/src/main/java/com/example/flightfinder/interceptor/ApiClient.kt
  AndroidProject/FlightFinder/app/src/main/java/com/example/flightfinder/interface/ApiInterface.kt
  AndroidProject/FlightFinder/app/src/main/java/com/example/flightfinder/model/User.kt
  AndroidProject/FlightFinder/app/src/main/java/com/example/flightfinder/model/UserList.kt
  AndroidProject/FlightFinder/app/src/main/java/com/example/flightfinder/response/CreateUserResponse.kt
  AndroidProject/FlightFinder/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  AndroidProject/FlightFinder/app/src/main/res/drawable/ic_image.xml
  AndroidProject/FlightFinder/app/src/main/res/drawable/ic_launcher_background.xml
  AndroidProject/FlightFinder/app/src/main/res/layout/activity_main.xml
  AndroidProject/FlightFinder/app/src/main/res/layout/list_items.xml
  AndroidProject/FlightFinder/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  AndroidProject/FlightFinder/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  AndroidProject/FlightFinder/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  AndroidProject/FlightFinder/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  AndroidProject/FlightFinder/app/src/main/res/values-night/themes.xml
  AndroidProject/FlightFinder/app/src/main/res/values/colors.xml
  AndroidProject/FlightFinder/app/src/main/res/values/strings.xml
  AndroidProject/FlightFinder/app/src/main/res/values/themes.xml
  AndroidProject/FlightFinder/app/src/test/java/com/example/flightfinder/ExampleUnitTest.kt
  AndroidProject/FlightFinder/build.gradle
  AndroidProject/FlightFinder/gradle.properties
  AndroidProject/FlightFinder/gradle/wrapper/gradle-wrapper.jar
  AndroidProject/FlightFinder/gradle/wrapper/gradle-wrapper.properties
  AndroidProject/FlightFinder/gradlew
  AndroidProject/FlightFinder/gradlew.bat
  AndroidProject/FlightFinder/settings.gradle
Labels: hacktoberfest, hacktoberfest-accepted

#35 Signup site added
  .idea/vcs.xml
  php/adminsignup/Capture.PNG
  php/adminsignup/admindelete.php
  php/adminsignup/adminlogin.php
  php/adminsignup/connection.php
  php/adminsignup/controllerUserData.php
  php/adminsignup/forgot-password.php
  php/adminsignup/images.jfif
  php/adminsignup/index.php
  php/adminsignup/logout-user.php
  php/adminsignup/new-password.php
  php/adminsignup/password-changed.php
  php/adminsignup/reset-code.php
  php/adminsignup/signup-user.php
  php/adminsignup/status.php
  php/adminsignup/style.css
  php/adminsignup/styleupdate.css
  php/adminsignup/user-otp.php
  php/adminsignup/wavestyle.css
Labels: hacktoberfest, hacktoberfest-accepted

#37 Web Development Project Added
  disney-character-game/README.md
  disney-character-game/images/din_djarin.png
  disney-character-game/images/disney_plus.png
  disney-character-game/images/favicon.ico
  disney-character-game/images/han_solo.png
  disney-character-game/images/lucasfilm.png
  disney-character-game/images/luke_skywalker.png
  disney-character-game/images/marvel studios.png
  disney-character-game/images/marvel-logo-34283.png
  disney-character-game/images/marvel.png
  disney-character-game/images/rey.png
  disney-character-game/index.html
  disney-character-game/index.js
  disney-character-game/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#36 Create LuckyNumber
  python/LuckyNumber
Labels: hacktoberfest, hacktoberfest-accepted

#40 Draw star using python
  python/star.py
Labels: hacktoberfest, hacktoberfest-accepted

#39 Added c++ folder and Some DSA codes in c++
  .DS_Store
  c++/.DS_Store
  c++/.vscode/c_cpp_properties.json
  c++/.vscode/settings.json
  c++/Binary Search Questions/.DS_Store
  c++/Binary Search Questions/BS_PivotElement.cpp
  c++/Binary Search Questions/BS_bookAllocation_advance.cpp
  c++/Binary Search Questions/BS_squar_root.cpp
  c++/Binary Search Questions/panter_partition_problem.cpp
  c++/Linked List/.DS_Store
  c++/Linked List/Doubly_LL.cpp
  c++/Linked List/Single_LL.cpp
  c++/Linked List/tempCodeRunnerFile.cpp
  c++/More Sort Questions/.DS_Store
  c++/More Sort Questions/.vscode/settings.json
  c++/More Sort Questions/Bubble_sort.cpp
  c++/More Sort Questions/Insertion_sort.cpp
  c++/More Sort Questions/MergeSort.cpp
  c++/More Sort Questions/Quick_Sort.cpp
  c++/More Sort Questions/Selection_Sort.cpp
  c++/Recurstion/.DS_Store
  c++/Recurstion/BinarySearch.cpp
  c++/Recurstion/Buble_Sort.cpp
  c++/Recurstion/Linear_Search.cpp
  c++/Recurstion/Number_Power.cpp
  c++/Recurstion/String_Reverse.cpp
  c++/Recurstion/Sum_of_arr.cpp
  c++/Recurstion/sorted_array.cpp
  c++/Recurstion/tempCodeRunnerFile.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#38 Password generator
  Password Generator.py
Labels: hacktoberfest, hacktoberfest-accepted

#41 Added magic 8 ball program
  python/magic8ball.py
Labels: hacktoberfest, hacktoberfest-accepted

#42 Added Tutle Canon project, fun with inputs
  python/turtle_canon.py
Labels: hacktoberfest, hacktoberfest-accepted

#43 Turtle Diamond Drawing side by side
  python/turtle_diamonds_drawing.py
Labels: hacktoberfest, hacktoberfest-accepted

#45 added length converter written in python
  python/Length Converter.py
Labels: hacktoberfest, hacktoberfest-accepted

#52 Create binarySearchRecursion.java
  binarySearchRecursion.java
Labels: hacktoberfest, hacktoberfest-accepted

#46 added weight converter written in python
  python/Weight Converter.py
Labels: hacktoberfest, hacktoberfest-accepted

#47 Flite Booking System Create Java
  java/Flight_Booking_Java/DomesticFlight.class
  java/Flight_Booking_Java/DomesticFlight.java
  java/Flight_Booking_Java/ExitListener.class
  java/Flight_Booking_Java/ExitListener.java
  java/Flight_Booking_Java/Flight_Booking_Java.iml
  java/Flight_Booking_Java/InternationalFlight.class
  java/Flight_Booking_Java/InternationalFlight.java
  java/Flight_Booking_Java/LoginPage.class
  java/Flight_Booking_Java/LoginPage.java
  java/Flight_Booking_Java/PrintTicket1.class
  java/Flight_Booking_Java/PrintTicket1.java
  java/Flight_Booking_Java/README.md
  java/Flight_Booking_Java/Save1.class
  java/Flight_Booking_Java/Save2.class
  java/Flight_Booking_Java/WindowUtilities.class
  java/Flight_Booking_Java/WindowUtilities.java
  java/Flight_Booking_Java/button1.class
  java/Flight_Booking_Java/button2.class
  java/Flight_Booking_Java/button3.class
  java/Flight_Booking_Java/db.java
  java/Flight_Booking_Java/img/business.jpg
  java/Flight_Booking_Java/img/business1.JPG
  java/Flight_Booking_Java/img/economic.jpg
  java/Flight_Booking_Java/img/economic1.JPG
  java/Flight_Booking_Java/map1.jpg
  java/Flight_Booking_Java/mouse0.class
  java/Flight_Booking_Java/mouse1.class
  java/Flight_Booking_Java/mouse2.class
  java/Flight_Booking_Java/mouse3.class
  java/Flight_Booking_Java/note_bg.gif
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/ExitListener.class
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/Flight_Booking_Java.iml
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/PrintTicket1.class
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/README.md
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/WindowUtilities.class
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/airline project.pdf
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/img/business.jpg
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/img/business1.JPG
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/img/economic.jpg
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/img/economic1.JPG
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/map1.jpg
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/note_bg.gif
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/readme.txt
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/save1
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/save2
  java/Flight_Booking_Java/out/production/Flight_Booking_Java/save2.txt
  java/Flight_Booking_Java/readme.txt
  java/Flight_Booking_Java/save1
  java/Flight_Booking_Java/save1.txt
  java/Flight_Booking_Java/save2
  java/Flight_Booking_Java/save2.txt
Labels: hacktoberfest, hacktoberfest-accepted

#59 Create Travelling Salesman Problem.py
  python/Travelling Salesman Problem.py
Labels: hacktoberfest, hacktoberfest-accepted

#54 Added File Segregator Script
  python/File_segregator.py
Labels: hacktoberfest, hacktoberfest-accepted

#48 Added Number of Anagrams code
  python/NumberofAnagrams.py
Labels: hacktoberfest, hacktoberfest-accepted

#49 Create prime_checker_in_python.py
  python/prime_checker_in_python.py
Labels: hacktoberfest, hacktoberfest-accepted

#53 add folder javascript and add simple function check prime number
  javascript/prime-number.js
Labels: hacktoberfest, hacktoberfest-accepted

#55 Added egg catcher game
  python/egg_catcher.py
Labels: hacktoberfest, hacktoberfest-accepted

#56 Create Trapping Rain water.py
  python/Trapping Rain water.py
Labels: hacktoberfest, hacktoberfest-accepted

#57 Create Sudoku.py
  python/Sudoku.py
Labels: hacktoberfest, hacktoberfest-accepted

#58 Create m Coloring Problem.py
  python/m Coloring Problem.py
Labels: hacktoberfest, hacktoberfest-accepted

#60 Create Greet_Bot.py
  Greet_Bot.py
Labels: hacktoberfest, hacktoberfest-accepted

#63 Python CV Basics Added
  CV_basics.py
Labels: hacktoberfest, hacktoberfest-accepted

#64 Create DFS.cpp
  c++/Recurstion/DFS.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#65 Even sum of Fibonacci Series (Nth term)
  java/Fibonacci_evensum.java
Labels: hacktoberfest, hacktoberfest-accepted

#66 Added Password Categorizer
  python/Pass_categorizer.py
Labels: hacktoberfest, hacktoberfest-accepted

#68 Text repetition N number
  Text repetition N number.py
Labels: hacktoberfest, hacktoberfest-accepted

#71 Added Binary Search code
  java/BinarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#69 created bankers_algo using cpp
  bankers_algo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#75 added c++ program to reverse a linked list
  c++/Linked List/Reverse_LinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#76 Added permutation.py
  python/permutation.py
Labels: hacktoberfest, hacktoberfest-accepted

#77 Create WeatherPrediction.ipynb
  python/WeatherPrediction.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#78 Added Car Racing game using JavaScript
  javascript/CarRacingGame/index.html
  javascript/CarRacingGame/script.js
  javascript/CarRacingGame/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#80 dice rolling game
  dice_rolling.py
Labels: hacktoberfest, hacktoberfest-accepted

#81 Create RecursiveQuicksort.java
  java/RecursiveQuicksort.java
Labels: hacktoberfest, hacktoberfest-accepted

#82 Program for Dijkstra Algorithm
  java/Dijkstra-Algo.java
Labels: hacktoberfest, hacktoberfest-accepted

#84 Added card Game
  cardGame.py
Labels: hacktoberfest, hacktoberfest-accepted

#85 Maintain Library data using Pickle
  python/LibraryData.py
Labels: hacktoberfest, hacktoberfest-accepted

#86 Added C files
  C/game.c
  C/guess_the_number.c
Labels: hacktoberfest, hacktoberfest-accepted

#87 Added two new python files
  python/Bubble_Sort.py
  python/snake_game.py
Labels: hacktoberfest, hacktoberfest-accepted

#88 Create Mergesort.py
  python/Mergesort.py
Labels: hacktoberfest, hacktoberfest-accepted

#89 Added Hotel Management app Using Java
  java/Hotel-Management-Project-Java-master/Main.java
  java/Hotel-Management-Project-Java-master/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#101 Implemented Queue With LinkedList, Classes
  python/Queue_LinkedList.py
Labels: hacktoberfest, hacktoberfest-accepted

#104 Added Tree ZigZag Traversal problem
  c++/Trees/ZigZag_Traversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#91 Calculator.py
  Calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#106 Create snakegame.py
  python/snakegame.py
Labels: hacktoberfest, hacktoberfest-accepted

#90 Opop
  c++/operator_overloading.cpp
  c++/overloadingC.cpp
Labels: hacktoberfest, hacktoberfest-accepted
